openapi: 3.1.0
info:
  title: BellaVita API
  version: 1.0.0
  description: API documentation for BellaVita project
servers: []
tags:
  - name: Auth
    description: Auth management
  - name: Users
    description: User management
  - name: Categories
    description: Category management
  - name: Products
    description: Product management
  - name: Orders
    description: Order management
  - name: Reviews
    description: Review management
  - name: Carts
    description: Cart management
  - name: AdminLogs
    description: Admin log management
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/auth/login:
    post:
      summary: Đăng nhập
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Đăng nhập thành công, trả về JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Sai tài khoản hoặc mật khẩu
  /api/auth/register:
    post:
      summary: Đăng ký
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                social_provider:
                  type: string
      responses:
        "201":
          description: Đăng ký thành công, trả về thông tin user mới tạo
        "400":
          description: Thông tin đăng ký không hợp lệ
  /api/users:
    get:
      summary: Lấy tất cả user
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách user
    post:
      summary: Tạo user mới
      tags: [Users]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                social_provider:
                  type: string
                status:
                  type: boolean
      responses:
        "201":
          description: User đã được tạo
  /api/users/{id}:
    get:
      summary: Lấy user theo id
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Thông tin user
        "404":
          description: Không tìm thấy user
    put:
      summary: Cập nhật user
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                social_provider:
                  type: string
                status:
                  type: boolean
      responses:
        "200":
          description: User đã được cập nhật
        "404":
          description: Không tìm thấy user
    delete:
      summary: Xóa user
      tags: [Users]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User đã được xóa
        "404":
          description: Không tìm thấy user
  /api/categories:
    get:
      summary: Lấy tất cả category
      tags: [Categories]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách category
    post:
      summary: Tạo category mới
      tags: [Categories]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
      responses:
        "201":
          description: Category đã được tạo
  /api/categories/{id}:
    get:
      summary: Lấy category theo id
      tags: [Categories]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin category
        "404":
          description: Không tìm thấy category
    put:
      summary: Cập nhật category
      tags: [Categories]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
      responses:
        "200":
          description: Category đã được cập nhật
        "404":
          description: Không tìm thấy category
    delete:
      summary: Xóa category
      tags: [Categories]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Category đã được xóa
        "404":
          description: Không tìm thấy category
  /api/products:
    get:
      summary: Lấy tất cả sản phẩm
      tags: [Products]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách sản phẩm
    post:
      summary: Tạo sản phẩm mới
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  format: float
                brand:
                  type: string
                skin_type:
                  type: string
                image_url:
                  type: string
                stock_quantity:
                  type: integer
                category_id:
                  type: integer
                barcode:
                  type: string
      responses:
        "201":
          description: Sản phẩm đã được tạo
  /api/products/{id}:
    get:
      summary: Lấy sản phẩm theo id
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin sản phẩm
        "404":
          description: Không tìm thấy sản phẩm
    put:
      summary: Cập nhật sản phẩm
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                  format: float
                brand:
                  type: string
                skin_type:
                  type: string
                image_url:
                  type: string
                stock_quantity:
                  type: integer
                category_id:
                  type: integer
                barcode:
                  type: string
      responses:
        "200":
          description: Sản phẩm đã được cập nhật
        "404":
          description: Không tìm thấy sản phẩm
    delete:
      summary: Xóa sản phẩm
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Sản phẩm đã được xóa
        "404":
          description: Không tìm thấy sản phẩm
  /api/orders:
    get:
      summary: Lấy tất cả đơn hàng
      tags: [Orders]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách đơn hàng
    post:
      summary: Tạo đơn hàng mới
      tags: [Orders]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                status:
                  type: boolean
                payment_method:
                  type: string
                total_amount:
                  type: number
                  format: float
      responses:
        "201":
          description: Đơn hàng đã được tạo
  /api/orders/{id}:
    get:
      summary: Lấy đơn hàng theo id
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin đơn hàng
        "404":
          description: Không tìm thấy đơn hàng
    put:
      summary: Cập nhật đơn hàng
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                status:
                  type: boolean
                payment_method:
                  type: string
                total_amount:
                  type: number
                  format: float
      responses:
        "200":
          description: Đơn hàng đã được cập nhật
        "404":
          description: Không tìm thấy đơn hàng
    delete:
      summary: Xóa đơn hàng
      tags: [Orders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Đơn hàng đã được xóa
        "404":
          description: Không tìm thấy đơn hàng
  /api/reviews:
    get:
      summary: Lấy tất cả review
      tags: [Reviews]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách review
    post:
      summary: Tạo review mới
      tags: [Reviews]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                product_id:
                  type: integer
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        "201":
          description: Review đã được tạo
  /api/reviews/{id}:
    get:
      summary: Lấy review theo id
      tags: [Reviews]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin review
        "404":
          description: Không tìm thấy review
    put:
      summary: Cập nhật review
      tags: [Reviews]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                product_id:
                  type: integer
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        "200":
          description: Review đã được cập nhật
        "404":
          description: Không tìm thấy review
    delete:
      summary: Xóa review
      tags: [Reviews]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Review đã được xóa
        "404":
          description: Không tìm thấy review
  /api/carts:
    get:
      summary: Lấy tất cả cart
      tags: [Carts]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách cart
    post:
      summary: Tạo cart mới
      tags: [Carts]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                status:
                  type: boolean
      responses:
        "201":
          description: Cart đã được tạo
  /api/carts/{id}:
    get:
      summary: Lấy cart theo id
      tags: [Carts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin cart
        "404":
          description: Không tìm thấy cart
    put:
      summary: Cập nhật cart
      tags: [Carts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                status:
                  type: boolean
      responses:
        "200":
          description: Cart đã được cập nhật
        "404":
          description: Không tìm thấy cart
    delete:
      summary: Xóa cart
      tags: [Carts]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Cart đã được xóa
        "404":
          description: Không tìm thấy cart
  /api/admin-logs:
    get:
      summary: Lấy tất cả admin log
      tags: [AdminLogs]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách admin log
    post:
      summary: Tạo admin log mới
      tags: [AdminLogs]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_id:
                  type: integer
                action_type:
                  type: string
                details:
                  type: string
      responses:
        "201":
          description: Admin log đã được tạo
  /api/admin-logs/{id}:
    get:
      summary: Lấy admin log theo id
      tags: [AdminLogs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin admin log
        "404":
          description: Không tìm thấy admin log
    put:
      summary: Cập nhật admin log
      tags: [AdminLogs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_id:
                  type: integer
                action_type:
                  type: string
                details:
                  type: string
      responses:
        "200":
          description: Admin log đã được cập nhật
        "404":
          description: Không tìm thấy admin log
    delete:
      summary: Xóa admin log
      tags: [AdminLogs]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Admin log đã được xóa
        "404":
          description: Không tìm thấy admin log
